export type SurveyStatus = 'Active' | 'Draft' | 'Paused' | 'Completed' | 'Rejected';
export type SurveyCategory = 'Social' | 'Product' | 'Brand' | 'Other';

export interface Survey {
  id: string;
  title: string;
  category: SurveyCategory;
  status: SurveyStatus;
  responsesCurrent: number;
  responsesTarget: number;
  rewardMnt: number;
  lengthMinutes: number;
  endsLabel: string;
  createdAt: string;

  // Admin / moderation fields
  companyId: string;
  companyName: string;

  // Detail-page fields
  description: string;
  endDate: string;
  trustLevel: 1 | 2 | 3 | 4 | 5;
  anonymous: boolean;
  completionRate: number;
  avgQuality: number;
  createdLabel: string;
}

export const DEMO_SURVEYS: Survey[] = [
  {
    id: 'SUR-001',
    title: 'Organizational Culture Survey',
    category: 'Other',
    status: 'Completed',
    responsesCurrent: 207,
    responsesTarget: 207,
    rewardMnt: 500,
    lengthMinutes: 3,
    endsLabel: '2 days ago',
    createdAt: '2026-02-15',
    companyId: 'co-003',
    companyName: 'Khan Bank',
    description: 'Internal culture pulse check across teams and leadership.',
    endDate: '2026-04-18',
    trustLevel: 1,
    anonymous: false,
    completionRate: 93,
    avgQuality: 4.4,
    createdLabel: '2 months ago',
  },
  {
    id: 'SUR-002',
    title: 'Market Trends Research',
    category: 'Social',
    status: 'Active',
    responsesCurrent: 8,
    responsesTarget: 77,
    rewardMnt: 2000,
    lengthMinutes: 4,
    endsLabel: 'in 13 days',
    createdAt: '2026-04-05',
    companyId: 'co-001',
    companyName: 'MCS Group',
    description: 'Understanding current market preferences and social media engagement patterns.',
    endDate: '2026-05-03',
    trustLevel: 2,
    anonymous: true,
    completionRate: 78,
    avgQuality: 4.1,
    createdLabel: '15 days ago',
  },
  {
    id: 'SUR-003',
    title: 'Social Responsibility Survey',
    category: 'Product',
    status: 'Active',
    responsesCurrent: 35,
    responsesTarget: 137,
    rewardMnt: 2000,
    lengthMinutes: 9,
    endsLabel: 'in 11 days',
    createdAt: '2026-04-03',
    companyId: 'co-003',
    companyName: 'Khan Bank',
    description: 'Measuring product impact on social and environmental responsibility.',
    endDate: '2026-05-01',
    trustLevel: 3,
    anonymous: true,
    completionRate: 82,
    avgQuality: 3.9,
    createdLabel: '17 days ago',
  },
  {
    id: 'SUR-004',
    title: 'Organizational Culture Survey',
    category: 'Social',
    status: 'Active',
    responsesCurrent: 179,
    responsesTarget: 184,
    rewardMnt: 1000,
    lengthMinutes: 8,
    endsLabel: 'in 27 days',
    createdAt: '2026-03-28',
    companyId: 'co-002',
    companyName: 'Mongolian Telecom',
    description: 'Cross-functional assessment of team dynamics, values, and collaboration.',
    endDate: '2026-05-17',
    trustLevel: 3,
    anonymous: false,
    completionRate: 89,
    avgQuality: 4.3,
    createdLabel: '23 days ago',
  },
  {
    id: 'SUR-005',
    title: 'Service Quality Assessment',
    category: 'Other',
    status: 'Draft',
    responsesCurrent: 0,
    responsesTarget: 332,
    rewardMnt: 500,
    lengthMinutes: 12,
    endsLabel: '—',
    createdAt: '2026-04-18',
    companyId: 'co-006',
    companyName: 'Tenger Insurance',
    description: 'Evaluating customer service quality across all support channels.',
    endDate: '2026-05-20',
    trustLevel: 1,
    anonymous: false,
    completionRate: 0,
    avgQuality: 0,
    createdLabel: '2 days ago',
  },
  {
    id: 'SUR-006',
    title: 'Digital Transformation Survey',
    category: 'Brand',
    status: 'Paused',
    responsesCurrent: 241,
    responsesTarget: 273,
    rewardMnt: 500,
    lengthMinutes: 5,
    endsLabel: 'in 30 days',
    createdAt: '2026-03-25',
    companyId: 'co-001',
    companyName: 'MCS Group',
    description: 'Brand perception during our ongoing digital transformation.',
    endDate: '2026-05-20',
    trustLevel: 2,
    anonymous: true,
    completionRate: 88,
    avgQuality: 4.0,
    createdLabel: '26 days ago',
  },
  {
    id: 'SUR-007',
    title: 'Digital Transformation Survey',
    category: 'Other',
    status: 'Active',
    responsesCurrent: 206,
    responsesTarget: 282,
    rewardMnt: 15_000,
    lengthMinutes: 3,
    endsLabel: 'in 10 days',
    createdAt: '2026-04-15',
    companyId: 'co-001',
    companyName: 'MCS Group',
    description: 'Quick pulse on digital adoption and tooling preferences.',
    endDate: '2026-05-20',
    trustLevel: 2,
    anonymous: false,
    completionRate: 73,
    avgQuality: 4.0,
    createdLabel: '5 days ago',
  },
  {
    id: 'SUR-008',
    title: 'Employee Satisfaction Survey',
    category: 'Other',
    status: 'Active',
    responsesCurrent: 34,
    responsesTarget: 56,
    rewardMnt: 1_000,
    lengthMinutes: 6,
    endsLabel: 'in 21 days',
    createdAt: '2026-04-12',
    companyId: 'co-003',
    companyName: 'Khan Bank',
    description: 'Pulse check on internal employee satisfaction and engagement.',
    endDate: '2026-05-12',
    trustLevel: 2,
    anonymous: true,
    completionRate: 81,
    avgQuality: 4.2,
    createdLabel: '5 days ago',
  },
  {
    id: 'SUR-009',
    title: 'Customer Satisfaction Survey',
    category: 'Social',
    status: 'Active',
    responsesCurrent: 328,
    responsesTarget: 393,
    rewardMnt: 2_000,
    lengthMinutes: 5,
    endsLabel: 'in 18 days',
    createdAt: '2026-04-10',
    companyId: 'co-002',
    companyName: 'Mongolian Telecom',
    description: 'Quarterly customer satisfaction measurement across all touchpoints.',
    endDate: '2026-05-09',
    trustLevel: 1,
    anonymous: false,
    completionRate: 84,
    avgQuality: 4.0,
    createdLabel: '5 days ago',
  },
  {
    id: 'SUR-010',
    title: 'Brand Perception Study',
    category: 'Brand',
    status: 'Active',
    responsesCurrent: 103,
    responsesTarget: 129,
    rewardMnt: 2_000,
    lengthMinutes: 7,
    endsLabel: 'in 9 days',
    createdAt: '2026-04-16',
    companyId: 'co-005',
    companyName: 'APU Company',
    description: 'Measuring brand perception and top-of-mind recall across consumer segments.',
    endDate: '2026-04-30',
    trustLevel: 1,
    anonymous: false,
    completionRate: 80,
    avgQuality: 4.1,
    createdLabel: '3 days ago',
  },
  {
    id: 'SUR-011',
    title: 'Promotional Campaign Feedback',
    category: 'Product',
    status: 'Rejected',
    responsesCurrent: 0,
    responsesTarget: 200,
    rewardMnt: 500,
    lengthMinutes: 4,
    endsLabel: '—',
    createdAt: '2026-04-08',
    companyId: 'co-007',
    companyName: 'Nomin Holdings',
    description: 'Flagged for misleading question wording during moderation review.',
    endDate: '2026-05-08',
    trustLevel: 1,
    anonymous: false,
    completionRate: 0,
    avgQuality: 0,
    createdLabel: '12 days ago',
  },
  {
    id: 'SUR-012',
    title: 'Mobile App Feedback',
    category: 'Product',
    status: 'Active',
    responsesCurrent: 91,
    responsesTarget: 150,
    rewardMnt: 800,
    lengthMinutes: 6,
    endsLabel: 'in 15 days',
    createdAt: '2026-04-06',
    companyId: 'co-008',
    companyName: 'Mobicom Corp',
    description: 'Collecting feedback on the latest mobile app release and new features.',
    endDate: '2026-05-06',
    trustLevel: 2,
    anonymous: true,
    completionRate: 79,
    avgQuality: 4.0,
    createdLabel: '14 days ago',
  },
  {
    id: 'SUR-013',
    title: 'SME Banking Needs',
    category: 'Product',
    status: 'Active',
    responsesCurrent: 52,
    responsesTarget: 120,
    rewardMnt: 1_500,
    lengthMinutes: 8,
    endsLabel: 'in 18 days',
    createdAt: '2026-04-02',
    companyId: 'co-004',
    companyName: 'Golomt Bank',
    description: 'Understanding small-business banking pain points and product opportunities.',
    endDate: '2026-05-10',
    trustLevel: 3,
    anonymous: false,
    completionRate: 82,
    avgQuality: 4.2,
    createdLabel: '18 days ago',
  },
  {
    id: 'SUR-014',
    title: 'Cashmere Buying Habits',
    category: 'Brand',
    status: 'Draft',
    responsesCurrent: 0,
    responsesTarget: 250,
    rewardMnt: 900,
    lengthMinutes: 5,
    endsLabel: '—',
    createdAt: '2026-04-15',
    companyId: 'co-009',
    companyName: 'Gobi Cashmere',
    description: 'Seasonal research into premium cashmere buying habits across markets.',
    endDate: '2026-05-25',
    trustLevel: 2,
    anonymous: false,
    completionRate: 0,
    avgQuality: 0,
    createdLabel: '5 days ago',
  },
  {
    id: 'SUR-015',
    title: 'Fuel Station Service Experience',
    category: 'Other',
    status: 'Active',
    responsesCurrent: 148,
    responsesTarget: 200,
    rewardMnt: 600,
    lengthMinutes: 3,
    endsLabel: 'in 7 days',
    createdAt: '2026-04-11',
    companyId: 'co-010',
    companyName: 'Shunkhlai Group',
    description: 'On-site service quality evaluation across retail fuel stations.',
    endDate: '2026-04-28',
    trustLevel: 1,
    anonymous: false,
    completionRate: 84,
    avgQuality: 4.1,
    createdLabel: '9 days ago',
  },
  {
    id: 'SUR-016',
    title: 'Corporate Credit Card Pulse',
    category: 'Product',
    status: 'Completed',
    responsesCurrent: 180,
    responsesTarget: 180,
    rewardMnt: 2_500,
    lengthMinutes: 6,
    endsLabel: '3 days ago',
    createdAt: '2026-03-18',
    companyId: 'co-011',
    companyName: 'TDB Bank',
    description: 'Satisfaction study for corporate credit card product holders.',
    endDate: '2026-04-17',
    trustLevel: 4,
    anonymous: false,
    completionRate: 96,
    avgQuality: 4.5,
    createdLabel: '1 month ago',
  },
  {
    id: 'SUR-017',
    title: 'Community Impact Study',
    category: 'Social',
    status: 'Paused',
    responsesCurrent: 68,
    responsesTarget: 300,
    rewardMnt: 1_200,
    lengthMinutes: 10,
    endsLabel: 'in 40 days',
    createdAt: '2026-03-20',
    companyId: 'co-012',
    companyName: 'Erdenes Mongol',
    description: 'Local community perception and impact of mining operations.',
    endDate: '2026-05-30',
    trustLevel: 3,
    anonymous: true,
    completionRate: 74,
    avgQuality: 3.8,
    createdLabel: '1 month ago',
  },
  {
    id: 'SUR-018',
    title: 'Digital Wallet Security',
    category: 'Product',
    status: 'Active',
    responsesCurrent: 45,
    responsesTarget: 150,
    rewardMnt: 1_800,
    lengthMinutes: 7,
    endsLabel: 'in 22 days',
    createdAt: '2026-04-08',
    companyId: 'co-004',
    companyName: 'Golomt Bank',
    description: 'Consumer trust and security perception for digital wallet products.',
    endDate: '2026-05-15',
    trustLevel: 3,
    anonymous: true,
    completionRate: 77,
    avgQuality: 4.0,
    createdLabel: '12 days ago',
  },
];

export function findSurveyById(id: string | undefined): Survey | undefined {
  if (!id) return undefined;
  const needle = id.toUpperCase();
  return DEMO_SURVEYS.find((s) => s.id.toUpperCase() === needle);
}
